language: ruby

rvm:
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - jruby-9.1.8.0

jdk:
  - oraclejdk8

services:
  - mongodb

sudo: false

bundler_args: --without development

# Gitter integration
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/4d6749e48eb60321640e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
